### ISSUE TITLE
Package.json has reference to dist/index.js

### ISSUE THREAD

**Issue by apalchys** [gdi2290/es7-reflect-metadata#1]
package.json still has reference to dist/index.js and 1.2.0 version doesn't work properly if install via npm.

**Comment by PatrickJS** [comment]
the output of `es7-reflect-metadata` is `{ Reflect:Reflect }` so you're better off using it globally with 
`es7-reflect-metadata/dist/browser` to include it in the `window` or `es7-reflect-metadata/dist/node` to include it to `global` for `node.js`. I'll update the repo

**Comment by PatrickJS** [comment]
fixed via https://github.com/gdi2290/es7-reflect-metadata/commit/5b18b34d055416ad83230337ad7ed951f1abad66
